'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Review

    Private _Id As Integer
    Public Property Id As Integer
        Get
            Return _Id
        End Get
        Private Set(ByVal value As Integer)
            _Id = value
        End Set
    End Property
    Public Property review As String
    Public Property rating As Rating

    Public Overridable Property Place As Place
    Public Overridable Property User As User

End Class
