'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Avatar
    Public Property Id As Integer
    Public Property image As String

    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
