'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DatabaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DatabaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Badges() As DbSet(Of Badge)
    Public Property Comments() As DbSet(Of Comment)
    Public Property Places() As DbSet(Of Place)
    Public Property Reviews() As DbSet(Of Review)
    Public Property Users() As DbSet(Of User)
    Public Property Visits() As DbSet(Of Visit)

End Class
